export const SOCIAL_PROOF_PEOPLE = [
  { name: "María", country: "México" },
  { name: "Camila", country: "Chile" },
  { name: "Valentina", country: "Argentina" },
  { name: "Sofía", country: "Colombia" },
  { name: "Fernanda", country: "Brasil" },
  { name: "Isabella", country: "Ecuador" },
  { name: "Daniela", country: "España" },
  { name: "Renata", country: "Bolivia" },
  { name: "Lucía", country: "Perú" },
  { name: "Antonella", country: "Uruguay" },
  { name: "Ximena", country: "Guatemala" },
  { name: "Paola", country: "República Dominicana" },
  { name: "Gabriela", country: "Costa Rica" },
  { name: "Carolina", country: "Paraguay" },
  { name: "Andrea", country: "Venezuela" },
];
